# Generated by Django 2.0.4 on 2018-04-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ereaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ereaccounts',
            name='ESIID',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
