"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
# Note Bokeh_SECRET_KEY must also be used/set when starting up Bokeh daemon
# e.g. BOKEH_SECRET_KEY='kitjOI83DgklnTuUykyHYABBCaV8oItJTZTQqVBav97G' bokeh serve .........  --session-ids external-signed
os.environ["BOKEH_SECRET_KEY"] = "kitjOI83DgklnTuUykyHYABBCaV8oItJTZTQqVBav97G"
os.environ["BOKEH_SIGN_SESSIONS"] = "True"

password_file_path = os.path.abspath(os.path.join(os.path.dirname( __file__ ), '..'))

def get_pw(pathname=password_file_path, filename='dbpw.txt'):
    path_and_file = os.path.join(pathname, filename)
    with open(path_and_file, 'r') as f:
        userid = f.readline().strip()
        pw = f.readline().strip()
        dbpath = f.readline().strip()
        dbname = f.readline().strip()
    return userid, pw, dbpath, dbname

userid, pw, dbpath, dbname = get_pw()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+$a6857r1+o-(hy)kazaxx-@ysxv!%r#7mbj++1y&6r-0o_3=m'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = False

ALLOWED_HOSTS = [#'52.55.228.166',
                 'ere.bigdataenergy.com',
                 '127.0.0.1'
                 ]
#ALLOWED_HOSTS = ['*']

# Application definition

SESSION_SECURITY_WARN_AFTER = 25*60
SESSION_SECURITY_EXPIRE_AFTER = 30*60
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


INSTALLED_APPS = [
    'dashboard.apps.DashboardConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'session_security',
#    'debug_toolbar',
]

MIDDLEWARE = [
#    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'session_security.middleware.SessionSecurityMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mysite.context_processors.version_number',
                'mysite.context_processors.application_company',
                'mysite.context_processors.application_name'
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# aws mssql setup
DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': dbname,
        'USER': userid,
        'PASSWORD': pw,
        'HOST': dbpath,
        'PORT': '1433',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATIC_DASHBOARD = os.path.join(STATIC_ROOT, 'dashboard/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'
